name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install  # Install all dependencies, not just specific ones
    - name: React Test
      id: react-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: React Test
        setup-command: npm install --save-dev jest jsdom jest-environment-jsdom react-scripts
        command: npm run test -- --watchAll=false  # Use npm run test and add --watchAll=false to avoid CI issues
        timeout: 60  # Increase timeout
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        REACT-TEST_RESULTS: "${{steps.react-test.outputs.result}}"
      with:
        runners: react-test
